Repository nomad-xyz/rust, pull requests merged in 2022-03, with the labels that each got.

#37 chore: update clap in CLI
  Cargo.lock
  Cargo.toml
  agents/processor/Cargo.toml
  chains/nomad-ethereum/src/bindings/home.rs
  chains/nomad-ethereum/src/bindings/replica.rs
  chains/nomad-ethereum/src/bindings/xappconnectionmanager.rs
  configuration/Cargo.toml
  nomad-types/Cargo.toml
  tools/balance-exporter/Cargo.toml
  tools/balance-exporter/src/main.rs
  tools/kms-cli/Cargo.toml
  tools/kms-cli/src/main.rs
Labels: chore, fix

#45 Prestwich/nomad id short ser
  nomad-types/CHANGELOG.md
  nomad-types/src/lib.rs
Labels: enhancement

#58 chore: configuration json chores
  .DS_Store
  .gitignore
  configuration/CHANGELOG.md
  configuration/configs/development.json
  configuration/configs/production.json
  configuration/configs/staging.json
  configuration/configs/test.json
Labels: chore

#59 fix: support aws signer from env
  configuration/src/agent/signer.rs
  fixtures/env.test
Labels: fix

#21 fix: use IntGaugeVec for watcher and home fail metrics and key by correct contracts
  agents/relayer/src/relayer.rs
  agents/watcher/src/watcher.rs
  nomad-base/src/agent.rs
  nomad-base/src/contract_sync/mod.rs
  nomad-base/src/metrics.rs
  nomad-base/src/settings/mod.rs
Labels: enhancement, observability

#60 fix: bump ethers to include aws fix
  Cargo.lock
  tools/kms-cli/src/main.rs
  tools/nomad-cli/src/subcommands/prove.rs
Labels: fix
