Repository nomad-xyz/rust, pull requests merged in 2022-05, with the labels that each got.

#145 chore: add a PR template
  .github/pull_request_template.md
Labels: chore

#147 Prestwich/betterer deser
  chains/nomad-ethereum/src/macros.rs
  configuration/CHANGELOG.md
  configuration/src/agent/signer.rs
  configuration/src/chains/ethereum.rs
  configuration/src/chains/mod.rs
  configuration/src/secrets.rs
  fixtures/env.test
  fixtures/secrets.json
  nomad-core/src/signer.rs
  nomad-types/src/lib.rs
Labels: refactor

#66 feature: support custom config files (outside of configuration crate)
  Cargo.lock
  agents/kathy/Cargo.toml
  agents/kathy/src/settings.rs
  agents/processor/Cargo.toml
  agents/processor/src/settings.rs
  agents/relayer/Cargo.toml
  agents/relayer/src/settings.rs
  agents/updater/Cargo.toml
  agents/updater/src/settings.rs
  agents/watcher/Cargo.toml
  agents/watcher/src/settings.rs
  configuration/src/lib.rs
  configuration/src/secrets.rs
  fixtures/env.external
  fixtures/env.test
  fixtures/external_config.json
  fixtures/external_secrets.json
  fixtures/test_secrets.json
  nomad-base/src/settings/macros.rs
  nomad-base/src/settings/mod.rs
  nomad-test/Cargo.toml
  nomad-test/src/test_utils.rs
Labels: enhancement, fix

#151 Move s3 to top-level of config
  Cargo.lock
  agents/processor/src/processor.rs
  configuration/CHANGELOG.md
  configuration/configs/development.json
  configuration/configs/production.json
  configuration/configs/staging.json
  configuration/data/definitions.ts
  configuration/data/types.rs
  configuration/src/agent/processor.rs
  configuration/src/lib.rs
  configuration/src/wasm/types.rs
  nomad-base/src/settings/macros.rs
Labels: refactor

#162 feat(config): add neon dev and staging to configs
  configuration/CHANGELOG.md
  configuration/configs/development.json
  configuration/configs/staging.json
Labels: config

#172 refactor: prevent convenience type from leaking into non-ser code
  configuration/src/gas/mod.rs
  configuration/src/lib.rs
Labels: enhancement, refactor

#155 feat(configuration): add `evmDefault` option for gas config + add gas configs for xdai, evmos, avalanche
  configuration/CHANGELOG.md
  configuration/configs/development.json
  configuration/configs/production.json
  configuration/configs/staging.json
  configuration/configs/test.json
  configuration/src/gas.rs
  configuration/src/gas/defaults.rs
  configuration/src/gas/mod.rs
  configuration/src/lib.rs
  nomad-base/src/settings/mod.rs
Labels: enhancement, configuration

#167 refactor(updater): updater gracefully handles errors
  agents/updater/src/updater.rs
Labels: refactor

#171 feat(agents): improve agent config
  Cargo.lock
  Cargo.toml
  agents/kathy/src/settings.rs
  configuration/CHANGELOG.md
  configuration/Cargo.toml
  configuration/src/agent/signer.rs
  configuration/src/chains/mod.rs
  configuration/src/secrets.rs
  configuration/src/traits/env.rs
  fixtures/env.test-signer-default
  fixtures/env.test-signer-mixed
  nomad-test/src/test_utils.rs
Labels: enhancement, configuration

#177 AWS improvements
  Cargo.lock
  agents/kathy/src/settings.rs
  agents/processor/src/processor.rs
  agents/processor/src/push.rs
  configuration/CHANGELOG.md
  configuration/src/agent/signer.rs
  configuration/src/secrets.rs
  fixtures/env.external
  fixtures/env.partial
  fixtures/env.test
  fixtures/env.test-signer-default
  fixtures/env.test-signer-mixed
  nomad-core/Cargo.toml
  nomad-core/src/signer.rs
  nomad-core/tests/signer_integration.rs
Labels: refactor

#178 feat: integrate Gelato and refactor transaction submission configuration
  Cargo.lock
  Cargo.toml
  accumulator/Cargo.toml
  accumulator/src/full.rs
  accumulator/src/lib.rs
  agents/kathy/src/settings.rs
  agents/processor/Cargo.toml
  agents/watcher/src/watcher.rs
  chains/nomad-ethereum/Cargo.toml
  chains/nomad-ethereum/src/bindings/home.rs
  chains/nomad-ethereum/src/bindings/replica.rs
  chains/nomad-ethereum/src/bindings/xappconnectionmanager.rs
  chains/nomad-ethereum/src/gelato/mod.rs
  chains/nomad-ethereum/src/gelato/types.rs
  chains/nomad-ethereum/src/gelato/utils.rs
  chains/nomad-ethereum/src/home.rs
  chains/nomad-ethereum/src/lib.rs
  chains/nomad-ethereum/src/macros.rs
  chains/nomad-ethereum/src/replica.rs
  chains/nomad-ethereum/src/submitter.rs
  chains/nomad-ethereum/src/xapp.rs
  configuration/CHANGELOG.md
  configuration/src/agent/signer.rs
  configuration/src/chains/ethereum/mod.rs
  configuration/src/chains/ethereum/submitter/gelato.rs
  configuration/src/chains/ethereum/submitter/mod.rs
  configuration/src/chains/mod.rs
  configuration/src/lib.rs
  configuration/src/secrets.rs
  configuration/src/utils.rs
  fixtures/env.external
  fixtures/env.partial
  fixtures/env.test
  fixtures/env.test-gelato-default
  fixtures/env.test-local-signer-default
  fixtures/env.test-local-signer-mixed
  fixtures/external_secrets.json
  fixtures/test_secrets.json
  gelato-relay/CHANGELOG.md
  gelato-relay/Cargo.toml
  gelato-relay/README.md
  gelato-relay/bin/status.rs
  gelato-relay/src/lib.rs
  gelato-relay/src/types.rs
  gelato-relay/tests/relay_integration_test.rs
  nomad-base/Cargo.toml
  nomad-base/src/lib.rs
  nomad-base/src/settings/chains.rs
  nomad-base/src/settings/mod.rs
  nomad-base/src/submitter.rs
  nomad-core/Cargo.toml
  nomad-core/src/signer.rs
  nomad-core/src/traits/mod.rs
  rust-toolchain
  tools/kms-cli/Cargo.toml
  tools/nomad-cli/Cargo.toml
  tools/nomad-cli/src/subcommands/prove.rs
Labels: enhancement, refactor
