Repository nomad-xyz/rust, pull requests merged in 2022-07, with the labels that each got.

#173 Fetch configs in configuration package build script
  Cargo.lock
  agents/relayer/src/relayer.rs
  configuration/CHANGELOG.md
  configuration/Cargo.toml
  configuration/build.rs
  configuration/configs/.gitignore
  configuration/configs/development.json
  configuration/configs/production.json
  configuration/configs/staging.json
  configuration/src/lib.rs
  configuration/src/secrets.rs
  nomad-core/src/traits/mod.rs
Labels: enhancement

#211 fix: prevent processor from attempting to run an empty select_all
  agents/processor/CHANGELOG.md
  agents/processor/src/processor.rs
  nomad-base/CHANGELOG.md
  nomad-base/src/agent.rs
Labels: bug, fix

#213 feature: add a tracing subscriber to capture and emit agent bootup events
  Cargo.lock
  agents/kathy/CHANGELOG.md
  agents/kathy/Cargo.toml
  agents/kathy/src/main.rs
  agents/processor/CHANGELOG.md
  agents/processor/Cargo.toml
  agents/processor/src/main.rs
  agents/relayer/CHANGELOG.md
  agents/relayer/Cargo.toml
  agents/relayer/src/main.rs
  agents/updater/CHANGELOG.md
  agents/updater/Cargo.toml
  agents/updater/src/main.rs
  agents/watcher/CHANGELOG.md
  agents/watcher/Cargo.toml
  agents/watcher/src/main.rs
  agents/watcher/src/watcher.rs
  chains/nomad-ethereum/Cargo.toml
  chains/nomad-ethereum/src/gas.rs
  chains/nomad-ethereum/src/home.rs
  chains/nomad-ethereum/src/macros.rs
  chains/nomad-ethereum/src/replica.rs
  chains/nomad-ethereum/src/xapp.rs
  configuration/Cargo.toml
  nomad-base/Cargo.toml
  nomad-base/src/agent.rs
  nomad-base/src/settings/macros.rs
  nomad-base/src/settings/trace/fmt.rs
  nomad-base/src/settings/trace/span_metrics.rs
  nomad-core/Cargo.toml
  nomad-test/Cargo.toml
  nomad-test/src/test_utils.rs
  nomad-types/Cargo.toml
  rust-toolchain
  tools/kms-cli/Cargo.toml
  tools/nomad-cli/Cargo.toml
Labels: enhancement

#218 feat(configuration): make config url overridable via env var
  Cargo.lock
  agents/kathy/CHANGELOG.md
  agents/kathy/src/main.rs
  agents/kathy/src/settings.rs
  agents/processor/CHANGELOG.md
  agents/processor/src/main.rs
  agents/processor/src/settings.rs
  agents/relayer/CHANGELOG.md
  agents/relayer/src/main.rs
  agents/relayer/src/settings.rs
  agents/updater/CHANGELOG.md
  agents/updater/src/main.rs
  agents/updater/src/settings.rs
  agents/watcher/CHANGELOG.md
  agents/watcher/src/main.rs
  agents/watcher/src/settings.rs
  nomad-base/CHANGELOG.md
  nomad-base/src/settings/macros.rs
  nomad-test/CHANGELOG.md
  nomad-test/Cargo.toml
  nomad-test/src/test_utils.rs
Labels: enhancement, configuration

#222 chore: update gelato sdk and resolve compilation issue
  Cargo.lock
  agents/kathy/src/settings.rs
  chains/nomad-ethereum/src/gelato.rs
Labels: chore

#209 refactor: remove deprecated deploy configuration keys
  configuration/CHANGELOG.md
  configuration/configs/test.json
  configuration/data/definitions.ts
  configuration/src/agent/processor.rs
  configuration/src/bridge.rs
  configuration/src/network.rs
  configuration/src/wasm/types.rs
  nomad-base/CHANGELOG.md
  nomad-base/src/metrics.rs
Labels: refactor

#225 fix: prevent some gigantic log lines by adding better display impls
  agents/processor/CHANGELOG.md
  agents/processor/src/processor.rs
  agents/relayer/CHANGELOG.md
  agents/relayer/src/relayer.rs
  agents/watcher/CHANGELOG.md
  agents/watcher/src/watcher.rs
  chains/nomad-ethereum/CHANGELOG.md
  chains/nomad-ethereum/src/home.rs
  chains/nomad-ethereum/src/replica.rs
  nomad-base/CHANGELOG.md
  nomad-base/src/home.rs
  nomad-base/src/replica.rs
  nomad-core/CHANGELOG.md
  nomad-core/src/traits/mod.rs
  nomad-test/CHANGELOG.md
  nomad-test/src/mocks/home.rs
  nomad-test/src/mocks/replica.rs
Labels: fix

#226 Prestwich/trace config source
  nomad-base/CHANGELOG.md
  nomad-base/src/settings/macros.rs
Labels: enhancement
