Repository nomad-xyz/rust, pull requests merged in 2022-06, with the labels that each got.

#194 Disable process retry
  agents/processor/CHANGELOG.md
  agents/processor/src/processor.rs
  chains/nomad-ethereum/src/macros.rs
  nomad-base/CHANGELOG.md
  nomad-base/src/nomad_db.rs
  nomad-core/CHANGELOG.md
  nomad-core/src/traits/encode.rs
Labels: refactor, fix

#189 feat(agents): add env var overrides for agent configs
  agents/kathy/CHANGELOG.md
  agents/kathy/src/settings.rs
  agents/processor/CHANGELOG.md
  agents/relayer/CHANGELOG.md
  agents/updater/CHANGELOG.md
  agents/watcher/CHANGELOG.md
  configuration/CHANGELOG.md
  configuration/configs/development.json
  configuration/configs/production.json
  configuration/configs/staging.json
  configuration/configs/test.json
  configuration/data/definitions.ts
  configuration/src/agent/kathy.rs
  configuration/src/agent/mod.rs
  configuration/src/agent/processor.rs
  configuration/src/agent/relayer.rs
  configuration/src/agent/updater.rs
  configuration/src/agent/watcher.rs
  configuration/src/wasm/types.rs
  fixtures/env.test-agents
  fixtures/external_config.json
  nomad-base/CHANGELOG.md
  nomad-base/bin/example.rs
  nomad-base/src/settings/macros.rs
Labels: enhancement, configuration

#202 refactor: add IRSA as first precedent for aws client creds
  Cargo.lock
  agents/processor/CHANGELOG.md
  agents/processor/src/processor.rs
  agents/processor/src/push.rs
  agents/watcher/src/watcher.rs
  chains/nomad-ethereum/src/macros.rs
  nomad-core/CHANGELOG.md
  nomad-core/Cargo.toml
  nomad-core/src/aws.rs
  nomad-core/src/lib.rs
  nomad-core/src/signer.rs
Labels: refactor, fix

#200 Integrate gelato as external crate
  Cargo.lock
  Cargo.toml
  agents/relayer/src/relayer.rs
  agents/watcher/src/watcher.rs
  chains/nomad-ethereum/CHANGELOG.md
  chains/nomad-ethereum/Cargo.toml
  chains/nomad-ethereum/src/bindings/home.rs
  chains/nomad-ethereum/src/bindings/replica.rs
  chains/nomad-ethereum/src/bindings/xappconnectionmanager.rs
  chains/nomad-ethereum/src/gelato.rs
  chains/nomad-ethereum/src/gelato/types.rs
  chains/nomad-ethereum/src/gelato/utils.rs
  chains/nomad-ethereum/src/macros.rs
  gelato-relay/CHANGELOG.md
  gelato-relay/Cargo.toml
  gelato-relay/README.md
  gelato-relay/bin/status.rs
  gelato-relay/src/lib.rs
  gelato-relay/src/types.rs
  gelato-relay/tests/relay_integration_test.rs
Labels: refactor
