Repository nomad-xyz/rust, pull requests merged in 2022-04, with the labels that each got.

#70 fix: s3 not s3Config in json
  configuration/configs/development.json
  configuration/configs/production.json
  configuration/configs/staging.json
  configuration/configs/test.json
Labels: fix

#71 fix: account for update gas variability and adjust gas limits
  chains/nomad-ethereum/src/home.rs
  chains/nomad-ethereum/src/replica.rs
  nomad-base/src/home.rs
  nomad-core/src/traits/home.rs
  nomad-test/src/mocks/home.rs
Labels: fix

#72 fix: 500 block paging limit for moonbeam
  configuration/configs/production.json
Labels: fix

#91 fix: contract sync for replicas use proper deploy heights
  nomad-base/src/settings/macros.rs
  nomad-base/src/settings/mod.rs
Labels: bug, fix

#96 feat(processor): processor takes list of subsidized replica chains
  agents/processor/src/processor.rs
  agents/processor/src/settings.rs
  configuration/configs/development.json
  configuration/configs/production.json
  configuration/configs/staging.json
  configuration/configs/test.json
  configuration/src/agent/processor.rs
  fixtures/env.test
  fixtures/secrets.json
Labels: enhancement

#100 chore: update ethers to latest master and relock
  Cargo.lock
Labels: chore

#111 feat(configs): add new dev and staging after failed homes situation
  Cargo.lock
  configuration/CHANGELOG.md
  configuration/Cargo.toml
  configuration/configs/development.json
  configuration/configs/staging.json
Labels: config

#110 refactor/fix: contract objects take two separate providers for reads and writes
  Cargo.lock
  agents/updater/src/submit.rs
  agents/updater/src/updater.rs
  chains/nomad-ethereum/src/home.rs
  chains/nomad-ethereum/src/lib.rs
  chains/nomad-ethereum/src/macros.rs
  chains/nomad-ethereum/src/replica.rs
  chains/nomad-ethereum/src/xapp.rs
  nomad-base/src/home.rs
  nomad-base/src/replica.rs
  nomad-base/src/settings/chains.rs
  nomad-base/src/settings/mod.rs
  nomad-base/src/xapp.rs
  tools/nomad-cli/src/subcommands/prove.rs
Labels: refactor, fix

#116 feat(config): add evmostestnet to dev config
  Cargo.lock
  configuration/CHANGELOG.md
  configuration/Cargo.toml
  configuration/configs/development.json
Labels: config

#69 fix: watcher counts updates inspected from HistorySync
  agents/watcher/src/watcher.rs
Labels: fix

#89 feat: bubble up signer instantiation errors
  agents/watcher/src/watcher.rs
  nomad-base/src/settings/chains.rs
  nomad-base/src/settings/macros.rs
  nomad-base/src/settings/mod.rs
  nomad-core/src/signer.rs
  nomad-types/src/lib.rs
Labels: fix
